---
title: "SAR TFM"
author: "Juan Carraha"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Cargar dataset

```{r}
url <- "https://github.com/brunopless/TFM-Equipo-4-BDDS/raw/main/entrega-3/2024_08_08_Consolidado_BCN.xlsx"
download.file(url, destfile = "2024_08_08_Consolidado_BCN.xlsx", mode = "wb")
```

```{r}
library(readxl)
data <- read_excel("2024_08_08_Consolidado_BCN.xlsx")
```

#Limpieza del dataset

##Recodificar propertyType

```{r}
# Aplicar one-hot encoding a la columna 'propertyType'
one_hot_propertyType <- model.matrix(~ `propertyType` - 1, data = data)

# Convertir el resultado a un dataframe y agregarlo al dataframe original
data <- cbind(data, one_hot_encoded)
```

##Recodificar status

```{r}
data$status[data$status == "goood"] <- "good"
```

Tenemos 5 valores perdidos.

```{r}
data <- data[!is.na(data$status), ]
```

```{r}
# Aplicar one-hot encoding a la columna 'status'
one_hot_status <- model.matrix(~ status - 1, data = data)

# Convertir el resultado a un dataframe y agregarlo al dataframe original
data <- cbind(data, one_hot_status)
```

##Limpiar media_precios_airbnb_500

Tenemos 4 valores perdidos.

```{r}
data <- data[!is.na(data$media_precios_airbnbs_500), ]
```

##Crear log_price
```{r}
# Crear una nueva columna con los logaritmos naturales
data$log_price <- log(data$price)
```
```{r}
numeric_vars <- names(data)[sapply(data, is.numeric)]
```

```{r}
# Variables a eliminar
remove_vars <- c("latitude", "longitude", "price", "Fecha extraccion", "log_price")

# Filtrando las variables
filtered_numeric_vars <- setdiff(numeric_vars, remove_vars)
```

```{r}
# Entrenar el modelo SAR con menos variables para optimizar el tiempo de ejecución
selected_vars <- c("floor", "size", "rooms", "bathrooms", "hasLift", "num_metro_500",
                  "num_parking_500", "num_airbnbs_500", "status_renew", "propertyType_studio")

formula <- as.formula(paste("log_price ~", paste(selected_vars, collapse=" + ")))
```

```{r}
library(spdep)
# Función para introducir una pequeña perturbación aleatoria
perturbate <- function(x) {
  x + runif(length(x), min = -1e-10, max = 1e-10)
}

# Introducir una pequeña perturbación aleatoria en las coordenadas
set.seed(42)  # Para reproducibilidad
datos$longitude <- perturbate(datos$longitude)
datos$latitude <- perturbate(datos$latitude)

```

```{r}
nb <- knn2nb(knearneigh(cbind(datos$longitude, datos$latitude), k=10))
```

```{r}
sar_model <- lagsarlm(formula = formula, data=datos, listw= nb2listw(nb, style = "W"))
```

```{r}
summary(sar_model)
```