---
title: "SAR"
author: "Juan Carraha"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Librerías necesarias
library(MASS)
library(spdep)
library(spatialreg)
library(readr)
```

```{r}
# Cargar datos
url <- "https://raw.githubusercontent.com/brunopless/TFM-Equipo-4-BDDS/main/entrega-3/df_bcn_imputado.csv"
data <- read_csv(url)
```

```{r}
# Variables numéricas
numeric_vars <- names(data)[sapply(data, is.numeric)]
```

```{r}
# Variables que se eliminarán
remove_vars <- c("...1", "log_price", "price_m2","price", "log_price_m2", "latitude", "longitude")
```

```{r}
# Variables independientes para el modelo SAR
variables_SAR <- setdiff(numeric_vars, remove_vars)
```

```{r}
# Función para añadir perturbación aleatoria a las coordenadas
perturbate <- function(x) {
  x + runif(length(x), min = -1e-10, max = 1e-10)
}

# Introducir la perturbación aleatoria en las coordenadas
set.seed(42)
data$longitude <- perturbate(data$longitude)
data$latitude <- perturbate(data$latitude)
```

```{r}
# Definir vecinos más cercanos para el modelo SAR
nb <- knn2nb(knearneigh(cbind(data$longitude, data$latitude), k=5))
```

```{r}
# Lista de variables dependientes para las cuatro iteraciones
dependent_vars <- c("price", "price_m2", "log_price", "log_price_m2")
```

```{r}
# Iterar sobre cada variable dependiente
for (dependent_var in dependent_vars) {
  
  # 1. Construir la fórmula con la variable dependiente actual
  formula <- as.formula(paste(dependent_var, "~", paste(variables_SAR, collapse=" + ")))
  print(paste("Modelo SAR con variable dependiente:", dependent_var))
  
  # 2. Ajustar el modelo SAR
  sar_model <- lagsarlm(formula = formula, data = data, listw = nb2listw(nb, style = "W"))
  
  # 3. Resumen del modelo
  summary(sar_model)
  
  # 4. Guardar el modelo en un archivo
  save(sar_model, file = paste0("modelo_sar_", dependent_var, ".RData"))
  saveRDS(sar_model, file = paste0("modelo_sar_", dependent_var, ".rds"))
  
  # 5. Calcular el pseudo-R² y el pseudo-R² ajustado
  residual_var <- var(residuals(sar_model))
  total_var <- var(data[[dependent_var]])
  
  pseudo_R2 <- 1 - (residual_var / total_var)
  
  n <- nrow(data)
  k <- length(variables_SAR)
  pseudo_R2_adj <- 1 - ((1 - pseudo_R2) * (n - 1) / (n - k - 1))
  
  # 6. Calcular el AIC
  aic_value <- AIC(sar_model)
  
  # 7. Calcular MAE y MAPE
  predictions <- predict(sar_model)
  
  mae_value <- mean(abs(predictions - data[[dependent_var]]))
  mape_value <- mean(abs((predictions - data[[dependent_var]]) / data[[dependent_var]])) * 100
  
  # 8. Mostrar resultados
  results <- list(
    variable_dependiente = dependent_var,
    pseudo_R2 = pseudo_R2,
    pseudo_R2_adj = pseudo_R2_adj,
    AIC = aic_value,
    MAE = mae_value,
    MAPE = mape_value
  )
  
  print(results)
}
```
